spring:
  application:
    name: payment-system-kotlin

  r2dbc:
    url: r2dbc:mysql://localhost:3307/test
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

logging:
  level:
    org:
      springframework:
        web: DEBUG
        r2dbc: DEBUG
        transaction: DEBUG

PSP:
  toss:
    secretKey: "test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6"
    url: "https://api.tosspayments.com"


