spring:
  application:
    name: payment-system-kotlin

  r2dbc:
    url: r2dbc:mysql://localhost:3307/test
    username: root
    password: 1234

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

PSP:
  toss:
    secretKey: test_sk_ALnQvDd2VJPLJLkZm4bx8Mj7X41m
    url: "https://api.tosspayments.com"


